name: pre-commit

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
      - name: "Setup Python"
        uses: actions/setup-python@v3
      - name: "Run pre-commit"
        uses: pre-commit/action@v3.0.0
